### ISSUE TITLE
Error in the subprocess.py

### ISSUE THREAD

**Issue by utsocial** [bitnami/bitnami-docker-laravel#106]
$ docker-compose up
Pulling mariadb (bitnami/mariadb:10.1)...
Traceback (most recent call last):
  File "site-packages\dockerpycreds\store.py", line 52, in _execute
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 403, in run
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by carrodher** [comment]
Hi, I am not able to reproduce the issue using the default _docker-compose.yaml_, it seems an issue with docker itself. What version are you using? Are you able to reproduce the issue after reinstalling Docker?
